[theme]

# Used to style primary interface elements.
primaryColor = "#EF0303" #red
#"#C93E3E" # soft red

# Background color for the main container.
backgroundColor = '#704214' #sepia yello hex code
#"rgba(254,248,239,1)" # sepia yellow

# Used as the background for most widgets.
secondaryBackgroundColor =  "#ebd2b9" # wheat  "#d7ab82" # yellow <-- not enough contrast

# Font color for the page.
textColor = "#000000" #black
#"#6e7074" # grey

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "sans serif"
